name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 1 * *"

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            deno: v2.x
    steps:
      - uses: actions/checkout@v6
      - uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}
      - run: deno lint
      - run: deno fmt --check
      - run: deno test
  test:
    needs: [check]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            deno: v2.x
          - os: ubuntu-latest
            deno: canary
          - os: windows-latest
            deno: v2.x
          - os: macos-latest
            deno: v2.x
    steps:
      - uses: actions/checkout@v6
      - uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}
      - run: deno test
